[pytest]

# Default CLI flags
addopts =
    -v
    -n 4
    --browsername=chromium
    --url=https://automationexercise.com/


# Discover tests only in the tests/ directory

testpaths = tests

# Mark definitions ()
markers =
    smoke:       Smoke / sanity tests (run on every build)
    regression:  Full regression suite
    security:    Security-related test cases
    negative:    Negative / sad-path test cases



