name: Run Python Playwright Tests with Allure Report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest # ಡಾಕರ್ ಕಂಟೇನರ್ ಬದಲಿಗೆ ನೇರವಾಗಿ ಕ್ಲೌಡ್ ಹೋಸ್ಟ್ ಬಳಸುತ್ತಿದ್ದೇವೆ

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-playwright allure-pytest

    - name: Install Playwright Browsers with Dependencies
      run: |
        playwright install --with-deps

    - name: Run pytest with Allure
      env:
        PYTHONPATH: .
      run: |
        pytest --alluredir=allure-results
      continue-on-error: true

    - name: Run Allure Action to Generate Report
      uses: allure-framework/allure-action@v0
      if: always()
      with:
        report-directory: "allure-report"
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
