name: Run Python Playwright Tests in Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    
    container:
      image: ://microsoft.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-playwright

    - name: Run pytest
      env:
        PYTHONPATH: .
      run: |
        pytest
